https://qiita.com/kotai2003/items/c8fa7e55230d0fa0cc8e

In [2]:
#from pycaret.datasets
import pandas as pd
dataset = pd.read_csv('winequality-white.csv',sep=";",encoding="utf-8")
dataset.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [3]:
data = dataset.sample(frac =0.95, random_state = 786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)
print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions: ' + str(data_unseen.shape))

Data for Modeling: (4653, 12)
Unseen Data For Predictions: (245, 12)

In [4]:
dataset.shape

(4898, 12)

In [6]:
dataset.sample(frac =0.95, random_state = 786)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1527,7.9,0.28,0.49,7.7,0.045,48.0,195.0,0.99540,3.04,0.55,11.0,6
4744,5.0,0.24,0.19,5.0,0.043,17.0,101.0,0.99438,3.67,0.57,10.0,5
2348,8.3,0.26,0.31,2.0,0.029,14.0,141.0,0.99077,2.95,0.77,12.2,6
2937,7.7,0.25,0.30,7.8,0.038,67.0,196.0,0.99555,3.10,0.50,10.1,5
4786,4.4,0.32,0.39,4.3,0.030,31.0,127.0,0.98904,3.46,0.36,12.8,8
...,...,...,...,...,...,...,...,...,...,...,...,...
1475,7.2,0.08,0.49,1.3,0.050,18.0,148.0,0.99450,3.46,0.44,10.2,6
2676,7.6,0.10,0.33,1.0,0.031,33.0,93.0,0.99094,3.06,0.68,11.2,6
472,6.6,0.24,0.29,2.0,0.023,19.0,86.0,0.99000,3.25,0.45,12.5,6
1237,7.3,0.24,0.39,3.6,0.024,35.0,116.0,0.99280,3.17,0.51,10.9,5
2086,8.2,0.17,0.32,1.5,0.050,17.0,101.0,0.99400,3.14,0.58,9.5,5

In [7]:
dataset.sample(frac =0.95, random_state = 786).reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.9,0.28,0.49,7.7,0.045,48.0,195.0,0.99540,3.04,0.55,11.0,6
1,5.0,0.24,0.19,5.0,0.043,17.0,101.0,0.99438,3.67,0.57,10.0,5
2,8.3,0.26,0.31,2.0,0.029,14.0,141.0,0.99077,2.95,0.77,12.2,6
3,7.7,0.25,0.30,7.8,0.038,67.0,196.0,0.99555,3.10,0.50,10.1,5
4,4.4,0.32,0.39,4.3,0.030,31.0,127.0,0.98904,3.46,0.36,12.8,8
...,...,...,...,...,...,...,...,...,...,...,...,...
4648,7.2,0.08,0.49,1.3,0.050,18.0,148.0,0.99450,3.46,0.44,10.2,6
4649,7.6,0.10,0.33,1.0,0.031,33.0,93.0,0.99094,3.06,0.68,11.2,6
4650,6.6,0.24,0.29,2.0,0.023,19.0,86.0,0.99000,3.25,0.45,12.5,6
4651,7.3,0.24,0.39,3.6,0.024,35.0,116.0,0.99280,3.17,0.51,10.9,5
4652,8.2,0.17,0.32,1.5,0.050,17.0,101.0,0.99400,3.14,0.58,9.5,5