In [1]:
import pandas as pd
train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/signate_titanic/train.tsv", sep="\t", index_col=0) # 学習用データ
test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/signate_titanic/test.tsv", sep="\t", index_col=0)   # 評価用データ
sample_submit = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/signate_titanic/sample_submit.tsv", sep="\t", index_col=0, header=None) # 応募用サンプルファイル

In [2]:
train.head()

    survived  pclass     sex   age  sibsp  parch     fare embarked
id
3          1       1  female  35.0      1      0  53.1000        S
4          0       3    male  35.0      0      0   8.0500        S
7          0       3    male   2.0      3      1  21.0750        S
9          1       2  female  14.0      1      0  30.0708        C
11         1       1  female  58.0      0      0  26.5500        S

In [3]:
train['survived'].value_counts()

0    266
1    179
Name: survived, dtype: int64

In [4]:
train.describe()

         survived      pclass         age       sibsp       parch        fare
count  445.000000  445.000000  360.000000  445.000000  445.000000  445.000000
mean     0.402247    2.296629   29.211583    0.546067    0.431461   33.959971
std      0.490903    0.834024   14.154300    1.195247    0.850489   52.079492
min      0.000000    1.000000    0.670000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.000000    0.000000    0.000000    7.925000
50%      0.000000    3.000000   28.000000    0.000000    0.000000   15.000000
75%      1.000000    3.000000   37.250000    1.000000    1.000000   31.387500
max      1.000000    3.000000   80.000000    8.000000    5.000000  512.329200

In [5]:
pd.get_dummies(train).corrwith(train["survived"])

survived      1.000000
pclass       -0.358097
age          -0.081394
sibsp        -0.045087
parch         0.079669
fare          0.258605
sex_female    0.559465
sex_male     -0.559465
embarked_C    0.182568
embarked_Q    0.005062
embarked_S   -0.172769
dtype: float64

In [6]:
train[['pclass', 'survived']].groupby(['pclass']).mean()

        survived
pclass
1       0.685185
2       0.443299
3       0.258333

In [7]:
train[['sex', 'survived']].groupby(['sex']).mean()

        survived
sex
female  0.775641
male    0.200692

In [8]:
data = pd.concat([train, test])

In [9]:
data

     survived  pclass     sex   age  sibsp  parch     fare embarked
id
3         1.0       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
7         0.0       3    male   2.0      3      1  21.0750        S
9         1.0       2  female  14.0      1      0  30.0708        C
11        1.0       1  female  58.0      0      0  26.5500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
885       NaN       3  female  39.0      0      5  29.1250        Q
886       NaN       2    male  27.0      0      0  13.0000        S
887       NaN       1  female  19.0      0      0  30.0000        S
889       NaN       1    male  26.0      0      0  30.0000        C
890       NaN       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [10]:
data['age'] = data['age'].fillna(data['age'].mean()) 
data['embarked'] = data['embarked'].fillna(data['embarked'].mode())

In [11]:
data = pd.get_dummies(data)
data

     survived  pclass   age  ...  embarked_C  embarked_Q  embarked_S
id                           ...
3         1.0       1  35.0  ...           0           0           1
4         0.0       3  35.0  ...           0           0           1
7         0.0       3   2.0  ...           0           0           1
9         1.0       2  14.0  ...           1           0           0
11        1.0       1  58.0  ...           0           0           1
..        ...     ...   ...  ...         ...         ...         ...
885       NaN       3  39.0  ...           0           1           0
886       NaN       2  27.0  ...           0           0           1
887       NaN       1  19.0  ...           0           0           1
889       NaN       1  26.0  ...           1           0           0
890       NaN       3  32.0  ...           0           1           0

[891 rows x 11 columns]

In [12]:
train = data.loc[train.index]
test = data.loc[test.index]
test = test.drop(["survived"], axis=1)

In [13]:
train.head()

    survived  pclass   age  sibsp  ...  sex_male  embarked_C  embarked_Q  embarked_S
id                                 ...
3        1.0       1  35.0      1  ...         0           0           0           1
4        0.0       3  35.0      0  ...         1           0           0           1
7        0.0       3   2.0      3  ...         1           0           0           1
9        1.0       2  14.0      1  ...         0           1           0           0
11       1.0       1  58.0      0  ...         0           0           0           1

[5 rows x 11 columns]

In [14]:
y = train["survived"] # 目的変数
X = train.drop(["survived"], axis=1) # 目的変数を除いたデータ

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

LogisticRegression()

In [19]:
pred = model.predict_proba(test)[:, 1] 
pred.shape

(446,)

In [ ]:
model.predict_proba(test)

In [21]:
sample_submit[1] = pred
sample_submit.to_csv('submit.tsv', header=None, sep='\t')